//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 05:05:28 PM UZT 
//


package uz.maroqand.ecology.ecoexpertise.mips.le_info_by_tin;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AuthInfo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="userSessionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="WS_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LE_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="msg"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TIN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="_LHASH_KEY_" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authInfo",
    "msg"
})
@XmlRootElement(name = "GetLegalEntityInfo")
public class GetLegalEntityInfo {

    @XmlElement(name = "AuthInfo")
    protected GetLegalEntityInfo.AuthInfo authInfo;
    @XmlElement(required = true)
    protected GetLegalEntityInfo.Msg msg;

    /**
     * Gets the value of the authInfo property.
     *
     * @return
     *     possible object is
     *     {@link GetLegalEntityInfo.AuthInfo }
     *
     */
    public GetLegalEntityInfo.AuthInfo getAuthInfo() {
        return authInfo;
    }

    /**
     * Sets the value of the authInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link GetLegalEntityInfo.AuthInfo }
     *
     */
    public void setAuthInfo(GetLegalEntityInfo.AuthInfo value) {
        this.authInfo = value;
    }

    /**
     * Gets the value of the msg property.
     *
     * @return
     *     possible object is
     *     {@link GetLegalEntityInfo.Msg }
     *
     */
    public GetLegalEntityInfo.Msg getMsg() {
        return msg;
    }

    /**
     * Sets the value of the msg property.
     *
     * @param value
     *     allowed object is
     *     {@link GetLegalEntityInfo.Msg }
     *
     */
    public void setMsg(GetLegalEntityInfo.Msg value) {
        this.msg = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="userSessionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="WS_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LE_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userSessionId",
        "wsid",
        "leid"
    })
    public static class AuthInfo {

        protected String userSessionId;
        @XmlElement(name = "WS_ID", required = true)
        protected String wsid;
        @XmlElement(name = "LE_ID", required = true)
        protected String leid;

        /**
         * Gets the value of the userSessionId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserSessionId() {
            return userSessionId;
        }

        /**
         * Sets the value of the userSessionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserSessionId(String value) {
            this.userSessionId = value;
        }

        /**
         * Gets the value of the wsid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWSID() {
            return wsid;
        }

        /**
         * Sets the value of the wsid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWSID(String value) {
            this.wsid = value;
        }

        /**
         * Gets the value of the leid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEID() {
            return leid;
        }

        /**
         * Sets the value of the leid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEID(String value) {
            this.leid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TIN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="_LHASH_KEY_" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tin",
        "lhashkey"
    })
    public static class Msg {

        @XmlElement(name = "TIN", required = true)
        protected String tin;
        @XmlElement(name = "_LHASH_KEY_", required = true)
        protected String lhashkey;

        /**
         * Gets the value of the tin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTIN() {
            return tin;
        }

        /**
         * Sets the value of the tin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTIN(String value) {
            this.tin = value;
        }

        /**
         * Gets the value of the lhashkey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLHASHKEY() {
            return lhashkey;
        }

        /**
         * Sets the value of the lhashkey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLHASHKEY(String value) {
            this.lhashkey = value;
        }

    }

}
