//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 05:05:28 PM UZT 
//


package uz.maroqand.ecology.ecoexpertise.mips.le_info_by_tin;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LE_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OKPO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="KFS_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KFS_DESC_UZ" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="KFS_DESC_RU" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="KFS_DESC_EN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="KOPF_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KOPF_DESC_UZ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KOPF_DESC_RU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KOPF_DESC_EN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOATO_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOATO_DESC_UZ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOATO_DESC_RU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOATO_DESC_EN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OKONH_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OKONH_DESC_UZ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OKONH_DESC_RU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OKONH_DESC_EN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OKED_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OKED_DESC_UZ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OKED_DESC_RU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OKED_DESC_EN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOOGU_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOOGU_DESC_UZ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOOGU_DESC_RU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SOOGU_DESC_EN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LE_NM_UZ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ACRON_UZ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="REG_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="REG_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LIQ_DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LIQ_NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ZIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ADDR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HEAD_NM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HEAD_TIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PHONE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EMAIL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AUTH_CAPITAL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AUTH_CAPITAL_US" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LE_TYP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SMALL_BIZ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EMP_AVR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TAX_CD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LE_STATUS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FOUNDER_NM1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FOUNDER_COUNTRY1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FOUNDER_NM2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FOUNDER_COUNTRY2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FOUNDER_NM3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FOUNDER_COUNTRY3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FOUNDER_NM4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FOUNDER_COUNTRY4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FOUNDER_NM5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FOUNDER_COUNTRY5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "leid",
    "tin",
    "okpo",
    "kfscd",
    "kfsdescuz",
    "kfsdescru",
    "kfsdescen",
    "kopfcd",
    "kopfdescuz",
    "kopfdescru",
    "kopfdescen",
    "soatocd",
    "soatodescuz",
    "soatodescru",
    "soatodescen",
    "okonhcd",
    "okonhdescuz",
    "okonhdescru",
    "okonhdescen",
    "okedcd",
    "okeddescuz",
    "okeddescru",
    "okeddescen",
    "soogucd",
    "soogudescuz",
    "soogudescru",
    "soogudescen",
    "lenmuz",
    "acronuz",
    "regdate",
    "regno",
    "liqdate",
    "liqno",
    "zip",
    "addr",
    "headnm",
    "headtin",
    "phone",
    "email",
    "authcapital",
    "authcapitalus",
    "letyp",
    "smallbiz",
    "empavr",
    "taxcd",
    "lestatus",
    "foundernm1",
    "foundercountry1",
    "foundernm2",
    "foundercountry2",
    "foundernm3",
    "foundercountry3",
    "foundernm4",
    "foundercountry4",
    "foundernm5",
    "foundercountry5"
})
@XmlRootElement(name = "LEGAL_ENTITY_INFORMATION", namespace = "urn:megaware:http:operation:B755BB65-B2A5-415F-8630-A8D70ECE7712")
public class LEGALENTITYINFORMATION {

    @XmlElement(name = "LE_ID")
    protected String leid;
    @XmlElement(name = "TIN")
    protected String tin;
    @XmlElement(name = "OKPO", required = true)
    protected String okpo;
    @XmlElement(name = "KFS_CD")
    protected String kfscd;
    @XmlElement(name = "KFS_DESC_UZ", required = true)
    protected String kfsdescuz;
    @XmlElement(name = "KFS_DESC_RU", required = true)
    protected String kfsdescru;
    @XmlElement(name = "KFS_DESC_EN", required = true)
    protected String kfsdescen;
    @XmlElement(name = "KOPF_CD")
    protected String kopfcd;
    @XmlElement(name = "KOPF_DESC_UZ")
    protected String kopfdescuz;
    @XmlElement(name = "KOPF_DESC_RU")
    protected String kopfdescru;
    @XmlElement(name = "KOPF_DESC_EN")
    protected String kopfdescen;
    @XmlElement(name = "SOATO_CD")
    protected String soatocd;
    @XmlElement(name = "SOATO_DESC_UZ")
    protected String soatodescuz;
    @XmlElement(name = "SOATO_DESC_RU")
    protected String soatodescru;
    @XmlElement(name = "SOATO_DESC_EN")
    protected String soatodescen;
    @XmlElement(name = "OKONH_CD")
    protected String okonhcd;
    @XmlElement(name = "OKONH_DESC_UZ")
    protected String okonhdescuz;
    @XmlElement(name = "OKONH_DESC_RU")
    protected String okonhdescru;
    @XmlElement(name = "OKONH_DESC_EN")
    protected String okonhdescen;
    @XmlElement(name = "OKED_CD")
    protected String okedcd;
    @XmlElement(name = "OKED_DESC_UZ")
    protected String okeddescuz;
    @XmlElement(name = "OKED_DESC_RU")
    protected String okeddescru;
    @XmlElement(name = "OKED_DESC_EN")
    protected String okeddescen;
    @XmlElement(name = "SOOGU_CD")
    protected String soogucd;
    @XmlElement(name = "SOOGU_DESC_UZ")
    protected String soogudescuz;
    @XmlElement(name = "SOOGU_DESC_RU")
    protected String soogudescru;
    @XmlElement(name = "SOOGU_DESC_EN")
    protected String soogudescen;
    @XmlElement(name = "LE_NM_UZ")
    protected String lenmuz;
    @XmlElement(name = "ACRON_UZ")
    protected String acronuz;
    @XmlElement(name = "REG_DATE")
    protected String regdate;
    @XmlElement(name = "REG_NO")
    protected String regno;
    @XmlElement(name = "LIQ_DATE")
    protected String liqdate;
    @XmlElement(name = "LIQ_NO")
    protected String liqno;
    @XmlElement(name = "ZIP")
    protected String zip;
    @XmlElement(name = "ADDR")
    protected String addr;
    @XmlElement(name = "HEAD_NM")
    protected String headnm;
    @XmlElement(name = "HEAD_TIN")
    protected String headtin;
    @XmlElement(name = "PHONE")
    protected String phone;
    @XmlElement(name = "EMAIL")
    protected String email;
    @XmlElement(name = "AUTH_CAPITAL")
    protected String authcapital;
    @XmlElement(name = "AUTH_CAPITAL_US")
    protected String authcapitalus;
    @XmlElement(name = "LE_TYP")
    protected String letyp;
    @XmlElement(name = "SMALL_BIZ")
    protected String smallbiz;
    @XmlElement(name = "EMP_AVR")
    protected String empavr;
    @XmlElement(name = "TAX_CD")
    protected String taxcd;
    @XmlElement(name = "LE_STATUS")
    protected String lestatus;
    @XmlElement(name = "FOUNDER_NM1")
    protected String foundernm1;
    @XmlElement(name = "FOUNDER_COUNTRY1")
    protected String foundercountry1;
    @XmlElement(name = "FOUNDER_NM2")
    protected String foundernm2;
    @XmlElement(name = "FOUNDER_COUNTRY2")
    protected String foundercountry2;
    @XmlElement(name = "FOUNDER_NM3")
    protected String foundernm3;
    @XmlElement(name = "FOUNDER_COUNTRY3")
    protected String foundercountry3;
    @XmlElement(name = "FOUNDER_NM4")
    protected String foundernm4;
    @XmlElement(name = "FOUNDER_COUNTRY4")
    protected String foundercountry4;
    @XmlElement(name = "FOUNDER_NM5")
    protected String foundernm5;
    @XmlElement(name = "FOUNDER_COUNTRY5")
    protected String foundercountry5;

    /**
     * Gets the value of the leid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEID() {
        return leid;
    }

    /**
     * Sets the value of the leid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEID(String value) {
        this.leid = value;
    }

    /**
     * Gets the value of the tin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIN() {
        return tin;
    }

    /**
     * Sets the value of the tin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIN(String value) {
        this.tin = value;
    }

    /**
     * Gets the value of the okpo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKPO() {
        return okpo;
    }

    /**
     * Sets the value of the okpo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKPO(String value) {
        this.okpo = value;
    }

    /**
     * Gets the value of the kfscd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKFSCD() {
        return kfscd;
    }

    /**
     * Sets the value of the kfscd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKFSCD(String value) {
        this.kfscd = value;
    }

    /**
     * Gets the value of the kfsdescuz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKFSDESCUZ() {
        return kfsdescuz;
    }

    /**
     * Sets the value of the kfsdescuz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKFSDESCUZ(String value) {
        this.kfsdescuz = value;
    }

    /**
     * Gets the value of the kfsdescru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKFSDESCRU() {
        return kfsdescru;
    }

    /**
     * Sets the value of the kfsdescru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKFSDESCRU(String value) {
        this.kfsdescru = value;
    }

    /**
     * Gets the value of the kfsdescen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKFSDESCEN() {
        return kfsdescen;
    }

    /**
     * Sets the value of the kfsdescen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKFSDESCEN(String value) {
        this.kfsdescen = value;
    }

    /**
     * Gets the value of the kopfcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKOPFCD() {
        return kopfcd;
    }

    /**
     * Sets the value of the kopfcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKOPFCD(String value) {
        this.kopfcd = value;
    }

    /**
     * Gets the value of the kopfdescuz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKOPFDESCUZ() {
        return kopfdescuz;
    }

    /**
     * Sets the value of the kopfdescuz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKOPFDESCUZ(String value) {
        this.kopfdescuz = value;
    }

    /**
     * Gets the value of the kopfdescru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKOPFDESCRU() {
        return kopfdescru;
    }

    /**
     * Sets the value of the kopfdescru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKOPFDESCRU(String value) {
        this.kopfdescru = value;
    }

    /**
     * Gets the value of the kopfdescen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKOPFDESCEN() {
        return kopfdescen;
    }

    /**
     * Sets the value of the kopfdescen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKOPFDESCEN(String value) {
        this.kopfdescen = value;
    }

    /**
     * Gets the value of the soatocd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOATOCD() {
        return soatocd;
    }

    /**
     * Sets the value of the soatocd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOATOCD(String value) {
        this.soatocd = value;
    }

    /**
     * Gets the value of the soatodescuz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOATODESCUZ() {
        return soatodescuz;
    }

    /**
     * Sets the value of the soatodescuz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOATODESCUZ(String value) {
        this.soatodescuz = value;
    }

    /**
     * Gets the value of the soatodescru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOATODESCRU() {
        return soatodescru;
    }

    /**
     * Sets the value of the soatodescru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOATODESCRU(String value) {
        this.soatodescru = value;
    }

    /**
     * Gets the value of the soatodescen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOATODESCEN() {
        return soatodescen;
    }

    /**
     * Sets the value of the soatodescen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOATODESCEN(String value) {
        this.soatodescen = value;
    }

    /**
     * Gets the value of the okonhcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKONHCD() {
        return okonhcd;
    }

    /**
     * Sets the value of the okonhcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKONHCD(String value) {
        this.okonhcd = value;
    }

    /**
     * Gets the value of the okonhdescuz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKONHDESCUZ() {
        return okonhdescuz;
    }

    /**
     * Sets the value of the okonhdescuz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKONHDESCUZ(String value) {
        this.okonhdescuz = value;
    }

    /**
     * Gets the value of the okonhdescru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKONHDESCRU() {
        return okonhdescru;
    }

    /**
     * Sets the value of the okonhdescru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKONHDESCRU(String value) {
        this.okonhdescru = value;
    }

    /**
     * Gets the value of the okonhdescen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKONHDESCEN() {
        return okonhdescen;
    }

    /**
     * Sets the value of the okonhdescen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKONHDESCEN(String value) {
        this.okonhdescen = value;
    }

    /**
     * Gets the value of the okedcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKEDCD() {
        return okedcd;
    }

    /**
     * Sets the value of the okedcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKEDCD(String value) {
        this.okedcd = value;
    }

    /**
     * Gets the value of the okeddescuz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKEDDESCUZ() {
        return okeddescuz;
    }

    /**
     * Sets the value of the okeddescuz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKEDDESCUZ(String value) {
        this.okeddescuz = value;
    }

    /**
     * Gets the value of the okeddescru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKEDDESCRU() {
        return okeddescru;
    }

    /**
     * Sets the value of the okeddescru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKEDDESCRU(String value) {
        this.okeddescru = value;
    }

    /**
     * Gets the value of the okeddescen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKEDDESCEN() {
        return okeddescen;
    }

    /**
     * Sets the value of the okeddescen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKEDDESCEN(String value) {
        this.okeddescen = value;
    }

    /**
     * Gets the value of the soogucd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOOGUCD() {
        return soogucd;
    }

    /**
     * Sets the value of the soogucd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOOGUCD(String value) {
        this.soogucd = value;
    }

    /**
     * Gets the value of the soogudescuz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOOGUDESCUZ() {
        return soogudescuz;
    }

    /**
     * Sets the value of the soogudescuz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOOGUDESCUZ(String value) {
        this.soogudescuz = value;
    }

    /**
     * Gets the value of the soogudescru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOOGUDESCRU() {
        return soogudescru;
    }

    /**
     * Sets the value of the soogudescru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOOGUDESCRU(String value) {
        this.soogudescru = value;
    }

    /**
     * Gets the value of the soogudescen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOOGUDESCEN() {
        return soogudescen;
    }

    /**
     * Sets the value of the soogudescen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOOGUDESCEN(String value) {
        this.soogudescen = value;
    }

    /**
     * Gets the value of the lenmuz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLENMUZ() {
        return lenmuz;
    }

    /**
     * Sets the value of the lenmuz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLENMUZ(String value) {
        this.lenmuz = value;
    }

    /**
     * Gets the value of the acronuz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACRONUZ() {
        return acronuz;
    }

    /**
     * Sets the value of the acronuz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACRONUZ(String value) {
        this.acronuz = value;
    }

    /**
     * Gets the value of the regdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREGDATE() {
        return regdate;
    }

    /**
     * Sets the value of the regdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREGDATE(String value) {
        this.regdate = value;
    }

    /**
     * Gets the value of the regno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREGNO() {
        return regno;
    }

    /**
     * Sets the value of the regno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREGNO(String value) {
        this.regno = value;
    }

    /**
     * Gets the value of the liqdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIQDATE() {
        return liqdate;
    }

    /**
     * Sets the value of the liqdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIQDATE(String value) {
        this.liqdate = value;
    }

    /**
     * Gets the value of the liqno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIQNO() {
        return liqno;
    }

    /**
     * Sets the value of the liqno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIQNO(String value) {
        this.liqno = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIP() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIP(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the addr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDR() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDR(String value) {
        this.addr = value;
    }

    /**
     * Gets the value of the headnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHEADNM() {
        return headnm;
    }

    /**
     * Sets the value of the headnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHEADNM(String value) {
        this.headnm = value;
    }

    /**
     * Gets the value of the headtin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHEADTIN() {
        return headtin;
    }

    /**
     * Sets the value of the headtin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHEADTIN(String value) {
        this.headtin = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHONE() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHONE(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAIL() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAIL(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the authcapital property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHCAPITAL() {
        return authcapital;
    }

    /**
     * Sets the value of the authcapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHCAPITAL(String value) {
        this.authcapital = value;
    }

    /**
     * Gets the value of the authcapitalus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAUTHCAPITALUS() {
        return authcapitalus;
    }

    /**
     * Sets the value of the authcapitalus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAUTHCAPITALUS(String value) {
        this.authcapitalus = value;
    }

    /**
     * Gets the value of the letyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLETYP() {
        return letyp;
    }

    /**
     * Sets the value of the letyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLETYP(String value) {
        this.letyp = value;
    }

    /**
     * Gets the value of the smallbiz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSMALLBIZ() {
        return smallbiz;
    }

    /**
     * Sets the value of the smallbiz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSMALLBIZ(String value) {
        this.smallbiz = value;
    }

    /**
     * Gets the value of the empavr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMPAVR() {
        return empavr;
    }

    /**
     * Sets the value of the empavr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMPAVR(String value) {
        this.empavr = value;
    }

    /**
     * Gets the value of the taxcd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXCD() {
        return taxcd;
    }

    /**
     * Sets the value of the taxcd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXCD(String value) {
        this.taxcd = value;
    }

    /**
     * Gets the value of the lestatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLESTATUS() {
        return lestatus;
    }

    /**
     * Sets the value of the lestatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLESTATUS(String value) {
        this.lestatus = value;
    }

    /**
     * Gets the value of the foundernm1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOUNDERNM1() {
        return foundernm1;
    }

    /**
     * Sets the value of the foundernm1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOUNDERNM1(String value) {
        this.foundernm1 = value;
    }

    /**
     * Gets the value of the foundercountry1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOUNDERCOUNTRY1() {
        return foundercountry1;
    }

    /**
     * Sets the value of the foundercountry1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOUNDERCOUNTRY1(String value) {
        this.foundercountry1 = value;
    }

    /**
     * Gets the value of the foundernm2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOUNDERNM2() {
        return foundernm2;
    }

    /**
     * Sets the value of the foundernm2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOUNDERNM2(String value) {
        this.foundernm2 = value;
    }

    /**
     * Gets the value of the foundercountry2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOUNDERCOUNTRY2() {
        return foundercountry2;
    }

    /**
     * Sets the value of the foundercountry2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOUNDERCOUNTRY2(String value) {
        this.foundercountry2 = value;
    }

    /**
     * Gets the value of the foundernm3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOUNDERNM3() {
        return foundernm3;
    }

    /**
     * Sets the value of the foundernm3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOUNDERNM3(String value) {
        this.foundernm3 = value;
    }

    /**
     * Gets the value of the foundercountry3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOUNDERCOUNTRY3() {
        return foundercountry3;
    }

    /**
     * Sets the value of the foundercountry3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOUNDERCOUNTRY3(String value) {
        this.foundercountry3 = value;
    }

    /**
     * Gets the value of the foundernm4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOUNDERNM4() {
        return foundernm4;
    }

    /**
     * Sets the value of the foundernm4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOUNDERNM4(String value) {
        this.foundernm4 = value;
    }

    /**
     * Gets the value of the foundercountry4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOUNDERCOUNTRY4() {
        return foundercountry4;
    }

    /**
     * Sets the value of the foundercountry4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOUNDERCOUNTRY4(String value) {
        this.foundercountry4 = value;
    }

    /**
     * Gets the value of the foundernm5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOUNDERNM5() {
        return foundernm5;
    }

    /**
     * Sets the value of the foundernm5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOUNDERNM5(String value) {
        this.foundernm5 = value;
    }

    /**
     * Gets the value of the foundercountry5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOUNDERCOUNTRY5() {
        return foundercountry5;
    }

    /**
     * Sets the value of the foundercountry5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOUNDERCOUNTRY5(String value) {
        this.foundercountry5 = value;
    }

}
