//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 05:05:28 PM UZT 
//


package uz.maroqand.ecology.ecoexpertise.mips.le_info_by_tin;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mip.leinfo.bytin package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mip.leinfo.bytin
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetLegalEntityInfo }
     * 
     */
    public GetLegalEntityInfo createGetLegalEntityInfo() {
        return new GetLegalEntityInfo();
    }

    /**
     * Create an instance of {@link GetLegalEntityInfo.AuthInfo }
     * 
     */
    public GetLegalEntityInfo.AuthInfo createGetLegalEntityInfoAuthInfo() {
        return new GetLegalEntityInfo.AuthInfo();
    }

    /**
     * Create an instance of {@link GetLegalEntityInfo.Msg }
     * 
     */
    public GetLegalEntityInfo.Msg createGetLegalEntityInfoMsg() {
        return new GetLegalEntityInfo.Msg();
    }

    /**
     * Create an instance of {@link LEGALENTITYINFORMATION }
     * 
     */
    public LEGALENTITYINFORMATION createLEGALENTITYINFORMATION() {
        return new LEGALENTITYINFORMATION();
    }

}
