//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.28 at 06:22:50 PM UZT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:megaware:/mediate/ips/PC/PersonDocInfoService/PersonDocInfoService.wsdl")
package uz.maroqand.ecology.ecoexpertise.mips.i_passport_info;
