
package uz.maroqand.ecology.core.service.integration.eimzo.yt_tsaproxy;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TsaProxyService", targetNamespace = "http://v1.tsaproxy.plugin.ss.capi.yt.uz/", wsdlLocation = "http://127.0.0.1:9090/ytcapiss/tsaproxy/v1?wsdl")
public class TsaProxyService
    extends Service
{

    private final static URL TSAPROXYSERVICE_WSDL_LOCATION;
    private final static WebServiceException TSAPROXYSERVICE_EXCEPTION;
    private final static QName TSAPROXYSERVICE_QNAME = new QName("http://v1.tsaproxy.plugin.ss.capi.yt.uz/", "TsaProxyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9090/ytcapiss/tsaproxy/v1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TSAPROXYSERVICE_WSDL_LOCATION = url;
        TSAPROXYSERVICE_EXCEPTION = e;
    }

    public TsaProxyService() {
        super(__getWsdlLocation(), TSAPROXYSERVICE_QNAME);
    }

    public TsaProxyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TSAPROXYSERVICE_QNAME, features);
    }

    public TsaProxyService(URL wsdlLocation) {
        super(wsdlLocation, TSAPROXYSERVICE_QNAME);
    }

    public TsaProxyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TSAPROXYSERVICE_QNAME, features);
    }

    public TsaProxyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TsaProxyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TsaProxy
     */
    @WebEndpoint(name = "TsaProxyPort")
    public TsaProxy getTsaProxyPort() {
        return super.getPort(new QName("http://v1.tsaproxy.plugin.ss.capi.yt.uz/", "TsaProxyPort"), TsaProxy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TsaProxy
     */
    @WebEndpoint(name = "TsaProxyPort")
    public TsaProxy getTsaProxyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://v1.tsaproxy.plugin.ss.capi.yt.uz/", "TsaProxyPort"), TsaProxy.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TSAPROXYSERVICE_EXCEPTION!= null) {
            throw TSAPROXYSERVICE_EXCEPTION;
        }
        return TSAPROXYSERVICE_WSDL_LOCATION;
    }

}
