
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (100, 100, 'TIJORAT TASHKILOTLARI – YURIDIK SHAXSLARNING TASHKILIY-HUQUQIY SHAKLLARI', 'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ЮРИДИЧЕСКИХ ЛИЦ, ЯВЛЯЮЩИХСЯ КОММЕРЧЕСКИМИ ОРГАНИЗАЦИЯМИ', '', '', null);
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (110, 110, 'Xususiy korxona', 'Частное предприятие', 'XK', 'ЧП', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (120, 120, 'Oilaviy korxona', 'Семейное предприятие', 'OK', 'СП', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (130, 130, 'Fermer xo‘jaligi', 'Фермерское хозяйство', 'FX', 'ФХ', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (140, 140, 'Dehqon xo‘jaligi (yuridik shaxs tashkil etgan holda)', 'Дехканское хозяйство (с образованием юридического лица)', 'DX', 'ДХ', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (151, 151, 'Xo‘jalik shirkati', 'Хозяйственное товарищество', 'XSh', 'ХТ', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (153, 153, 'Aksiyadorlik jamiyati', 'Акционерное общество', 'AJ', 'АО', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (160, 160, 'Unitar korxona', 'Унитарное предприятие', 'UK', 'УП', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (161, 160, 'Davlat unitar korxonasi', 'Государственное унитарное предприятие', 'DUK', 'ГУП', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (170, 170, 'Ishlab chiqarish kooperativi', 'Производственный кооператив ', 'IChK', 'ПК', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (190, 190, 'Boshqa guruhlarga kiritilmagan tijoratchi tashkilot', 'Коммерческая организация, не включенная в другие группировки', '', '', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (191, 190, 'To`liq shirkat', 'Полная товарищества', 'TSh', 'ПТ', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (192, 190, 'Komandit shirkat', 'Коммандитная товарищества', 'KSh', 'КТ', '100');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (200, 200, 'NOTIJORAT TASHKILOTLARI – YURIDIK SHAXSLARNING TASHKILIY-HUQUQIY SHAKLLARI', 'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ЮРИДИЧЕСКИХ ЛИЦ, ЯВЛЯЮЩИХСЯ НЕКОММЕРЧЕСКИМИ ОРГАНИЗАЦИЯМИ', '', '', null);
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (210, 210, 'Jamoat birlashmasi', 'Общественное объединение ', 'JB', 'ОО', '200');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (220, 220, 'Fuqarolarning o‘zini-o‘zi boshqarish organi', 'Орган самоуправления граждан', 'FO`O`BO', 'ОСГ', '200');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (230, 230, 'Matlubot kooperativi', 'Потребительский кооператив', 'MK', '', '200');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (240, 240, 'Xususiy uy-joy mulkdorlarining shirkati', 'Товарищество частных собственников жилья', 'XUJMSh', 'ТЧСЖ', '200');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (250, 250, 'Jamoat fondi', 'Общественный фонд', 'JF', 'ОФ', '200');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (260, 260, 'Yuridik shaxslarning birlashmasi (uyushma)', 'Объединение юридических лиц (ассоциация, союз)', '', '', '200');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (270, 270, 'Muassasa', 'Учреждение', '', '', '200');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (271, 270, 'Maktabgacha ta''lim muassasasi', 'Дошкольное образовательное учреждение', 'MTM', 'ДОУ', '200');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (272, 270, 'Nodavlat ta''lim muassasasi', 'Негосударственное образовательное учреждение', 'NTM', 'НОУ', '200');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (290, 290, 'Boshqa guruhlarga kiritilmagan notijorat tashkilot', 'Некоммерческая организация, не включенная в другие группировки', '', '', '200');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (300, 300, 'YURIDIK SHAXS BO‘LMAGAN ALOHIDA BO‘LINMALARNING TASHKILIY-HUQUQIY SHAKLLARI', 'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ ОБОСОБЛЕННЫХ ПОДРАЗДЕЛЕНИЙ, НЕ ЯВЛЯЮЩИХСЯ ЮРИДИЧЕСКИМИ ЛИЦАМИ', '', '', null);
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (310, 310, 'Filial', 'Филиал', 'f-l', 'ф-л', '300');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (320, 320, 'Vakolatxona', 'Представительство', '', '', '300');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (330, 330, 'Filial yoki vakolatxona sifatida rasmiylashtirilmagan alohida bo‘linma', 'Обособленное подразделение, не оформленное в качестве филиала или представительства ', '', '', '300');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (400, 400, 'FUQAROLARNING TIJORAT FAOLIYATINING TASHKILIY-HUQUQIY SHAKLLARI', 'ОРГАНИЗАЦИОННО-ПРАВОВЫЕ ФОРМЫ КОММЕРЧЕСКОЙ ДЕЯТЕЛЬНОСТИ ГРАЖДАН', '', '', null);
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (410, 410, 'Yuridik shaxs tashkil etmagan dehqon xo‘jaligi', 'Дехканское хозяйство, без образования юридического лица', 'DX', 'ДХ', '400');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (420, 420, 'Yakka tartibdagi tadbirkor', 'Индивидуальный предприниматель', 'YaTT', 'ИП', '400');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (430, 430, 'Yuridik shaxs tashkil etmagan oilaviy tadbirkorlik', 'Семейное предпринимательство, без образования юридического лица', 'OT', 'СП', '400');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (440, 440, 'Hunarmandchilik faoliyati', 'Ремесленническая деятельность', 'HFS', 'CРД', '400');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (450, 450, 'Tijoriy faoliyat uchun belgilangan tovarlarni olib keluvchi yakka tartibdagi tadbirkor', 'Индивидуальный предприниматель, завозящий товары, предназначенные для коммерческой деятельности', 'YaTT TK', 'ИП ЗТ', '400');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1000, 1000, 'TIJORAT TASHKILOTLARI', 'КОММЕРЧЕСКИЕ ОРГАHИЗАЦИИ', '', '', null);
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1010, 1010, 'Xususiy korxona', 'Частные предприятия', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1100, 1100, 'Korxona', 'Предприятия', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1110, 1110, 'Davlat korxonasi', 'Государственные предприятия', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1120, 1120, 'Jamoat birlashmalari (tashkilotlar)', 'Предприятия общественных объединений (организаций)', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1130, 1130, 'Matlubot kooperatsiyasi tashkiloti', 'Предприятия потребительской кооперации', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1140, 1140, 'Mahalla tashkilotlari', 'Махаллинские предприятия', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1150, 1150, 'Aksionerlik jamiyatlari', 'Акционерные общества', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1151, 1151, 'Davlat aksiyadorlik jamiyati', 'Государственно- акционерные общества', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1152, 1152, 'Aralash shirkat va mas''uliyati cheklangan jamiyat', 'Смешанные товарищества и общества с ограниченной ответственностью', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1153, 1153, 'To''liq shirkat', 'Полные товарищества', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1170, 1170, 'Ishlab chiqarish kooperativlari', 'Производственные кооперативы', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1180, 1180, 'Dehqon va fermer xo''jaliklari', 'Дехканские и фермерские хозяйства', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1190, 1190, 'Oilaviy korxona', 'Семейное предприятие', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1200, 1200, 'Unitar korxona', 'Унитарное предприятие', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1210, 1210, 'Uyushmalar (ittifoqlar)', 'Ассоциации (союзы)', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1220, 1220, 'Konsernlar', 'Концерны', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1230, 1230, 'Aksiyadorlik jamiyatlari birlashmasi', 'Объединения предприятий акционерного общества', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1231, 1231, 'Aralash shirkatlar birlashmasi', 'Объединения предприятий  смешанного товарищества', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1232, 1232, 'To''liq shirkatlar birlashmasi', 'Объединения предприятий  полного товарищества', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1240, 1240, 'Lizing kompaniyalar', 'Лизинговые компании', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1250, 1250, 'Korporatsiyalar', 'Корпорации', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1260, 1260, 'Holding kompaniyalar', 'Холдинговые компании', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1270, 1270, 'Xususiylashtirilgan investitsion fondlar', 'Приватизированные инвестиционные фонды', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1290, 1290, 'Boshqa tijorat tashkilotlari', 'Другие коммерческие организации', '', '', '1000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1521, 152, 'Mas''uliyati cheklangan jamiyat', 'Общество с ограниченной ответственностью', 'MChJ', 'ООО', null);
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (1522, 152, 'Qo''shimcha mas''uliyatli jamiyat', 'Общество с дополнительной ответственностью', 'QMJ', 'ОДО', null);
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2000, 2000, 'NOTIJORAT KORXONALAR', 'HЕКОММЕРЧЕСКИЕ ОРГАHИЗАЦИИ', '', '', null);
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2100, 2100, 'Davlat muassasalari', 'Государственные учреждения', '', '', '2000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2110, 2110, 'Fuqarolar o''z-o''zini boshqarish muassasalari', 'Учреждения самоуправлений граждан', '', '', '2000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2200, 2200, 'Jamoat birlashmalari (tashkilotlar)', 'Общественные объединения (организации)', '', '', '2000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2300, 2300, 'Jamoat birlashmalari muassasalari (tashkilotlar)', 'Учреждения общественных объединений (организаций)', '', '', '2000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2400, 2400, 'Jamoat birlashmalari, uyushmalar, ittifoq va fondlar', 'Объединения обществ, союзов, ассоциаций и фондов', '', '', '2000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2500, 2500, 'Iste''mol jamiyati uyushmalari', 'Союзы потребительских обществ', '', '', '2000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2600, 2600, 'Iste''mol kooperativ muassasalari', 'Учреждения потребительской кооперации', '', '', '2000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2700, 2700, 'Moliya-sanoat guruhlari', 'Финансово-промышленные группы', '', '', '2000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2800, 2800, 'Davlat korxonalari', 'Государственные предприятия', '', '', '2000');
INSERT INTO public.sys_opf (id, code, name, name_ru, name_short, name_short_ru, parent_id) VALUES (2900, 2900, 'Boshqa notijorat tashkilotlar', 'Другие некоммерческие организации', '', '', '2000');
