//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 02:10:05 AM UZT 
//


package uz.maroqand.ecology.ecoexpertise.mips.i_tax_info_by_pin;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mip.leinfo.bytin package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mip.leinfo.bytin
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTaxInfobyPinReq }
     * 
     */
    public GetTaxInfobyPinReq createGetTaxInfobyPinReq() {
        return new GetTaxInfobyPinReq();
    }

    /**
     * Create an instance of {@link GetTaxInfobyPinRes }
     * 
     */
    public GetTaxInfobyPinRes createGetTaxInfobyPinRes() {
        return new GetTaxInfobyPinRes();
    }

    /**
     * Create an instance of {@link GetTaxInfobyPinRes.Root }
     * 
     */
    public GetTaxInfobyPinRes.Root createGetTaxInfobyPinResRoot() {
        return new GetTaxInfobyPinRes.Root();
    }

    /**
     * Create an instance of {@link GetTaxInfobyPinReq.AuthInfo }
     * 
     */
    public GetTaxInfobyPinReq.AuthInfo createGetTaxInfobyPinReqAuthInfo() {
        return new GetTaxInfobyPinReq.AuthInfo();
    }

    /**
     * Create an instance of {@link GetTaxInfobyPinRes.Root.List }
     * 
     */
    public GetTaxInfobyPinRes.Root.List createGetTaxInfobyPinResRootList() {
        return new GetTaxInfobyPinRes.Root.List();
    }

}
