//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.29 at 01:11:24 AM UZT 
//


package uz.maroqand.ecology.ecoexpertise.mips.i_tax_info_by_tin;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="err_code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="err_text" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="root"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="list"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="branch_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="doc_num" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="pin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="reg_date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errCode",
    "errText",
    "root"
})
@XmlRootElement(name = "getTaxInfobyTinRes", namespace = "urn:megaware:http:operation:F3FC560C-E860-4DDA-9A6D-8E42538E07BE")
public class GetTaxInfobyTinRes {

    @XmlElement(name = "err_code", required = true)
    protected String errCode;
    @XmlElement(name = "err_text", required = true)
    protected String errText;
    @XmlElement(required = true)
    protected GetTaxInfobyTinRes.Root root;

    /**
     * Gets the value of the errCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * Sets the value of the errCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setErrCode(String value) {
        this.errCode = value;
    }

    /**
     * Gets the value of the errText property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getErrText() {
        return errText;
    }

    /**
     * Sets the value of the errText property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setErrText(String value) {
        this.errText = value;
    }

    /**
     * Gets the value of the root property.
     *
     * @return
     *     possible object is
     *     {@link GetTaxInfobyTinRes.Root }
     *
     */
    public GetTaxInfobyTinRes.Root getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     *
     * @param value
     *     allowed object is
     *     {@link GetTaxInfobyTinRes.Root }
     *
     */
    public void setRoot(GetTaxInfobyTinRes.Root value) {
        this.root = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="list"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="branch_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="doc_num" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="pin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="reg_date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "list"
    })
    public static class Root {

        @XmlElement(required = true)
        protected GetTaxInfobyTinRes.Root.List list;

        /**
         * Gets the value of the list property.
         *
         * @return
         *     possible object is
         *     {@link GetTaxInfobyTinRes.Root.List }
         *
         */
        public GetTaxInfobyTinRes.Root.List getList() {
            return list;
        }

        /**
         * Sets the value of the list property.
         *
         * @param value
         *     allowed object is
         *     {@link GetTaxInfobyTinRes.Root.List }
         *
         */
        public void setList(GetTaxInfobyTinRes.Root.List value) {
            this.list = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="branch_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="doc_num" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="pin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="reg_date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "branchId",
            "docNum",
            "pin",
            "regDate",
            "status"
        })
        public static class List {

            @XmlElement(name = "branch_id", required = true)
            protected String branchId;
            @XmlElement(name = "doc_num", required = true)
            protected String docNum;
            @XmlElement(required = true)
            protected String pin;
            @XmlElement(name = "reg_date", required = true)
            protected String regDate;
            @XmlElement(required = true)
            protected String status;

            /**
             * Gets the value of the branchId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBranchId() {
                return branchId;
            }

            /**
             * Sets the value of the branchId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBranchId(String value) {
                this.branchId = value;
            }

            /**
             * Gets the value of the docNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDocNum() {
                return docNum;
            }

            /**
             * Sets the value of the docNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDocNum(String value) {
                this.docNum = value;
            }

            /**
             * Gets the value of the pin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPin() {
                return pin;
            }

            /**
             * Sets the value of the pin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPin(String value) {
                this.pin = value;
            }

            /**
             * Gets the value of the regDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegDate() {
                return regDate;
            }

            /**
             * Sets the value of the regDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegDate(String value) {
                this.regDate = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

        }

    }

}
