//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.29 at 01:11:24 AM UZT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:megaware:/mediate/ips/STC/GetTaxInfobyTin/GetTaxInfobyTin.wsdl")
package uz.maroqand.ecology.ecoexpertise.mips.i_tax_info_by_tin;
