
package uz.maroqand.ecology.core.integration.upay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "STWS", targetNamespace = "http://st.apus.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface STWS {


    /**
     * 
     * @param prepaymentRequest
     * @return
     *     returns uz.maroqand.ecology.core.integration.upay.PrepaymentResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prepayment", targetNamespace = "http://st.apus.com/", className = "uz.maroqand.ecology.core.integration.upay.Prepayment")
    @ResponseWrapper(localName = "prepaymentResponse", targetNamespace = "http://st.apus.com/", className = "uz.maroqand.ecology.core.integration.upay.PrepaymentResponse")
    @Action(input = "http://st.apus.com/STWS/prepaymentRequest", output = "http://st.apus.com/STWS/prepaymentResponse")
    public uz.maroqand.ecology.core.integration.upay.PrepaymentResponse.Return prepayment(
            @WebParam(name = "PrepaymentRequest", targetNamespace = "")
                    uz.maroqand.ecology.core.integration.upay.Prepayment.PrepaymentRequest prepaymentRequest);


    /**
     *
     * @param confirmPaymentRequest
     * @return
     *     returns uz.maroqand.ecology.core.integration.upay.ConfirmPaymentResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmPayment", targetNamespace = "http://st.apus.com/", className = "uz.maroqand.ecology.core.integration.upay.ConfirmPayment")
    @ResponseWrapper(localName = "confirmPaymentResponse", targetNamespace = "http://st.apus.com/", className = "uz.maroqand.ecology.core.integration.upay.ConfirmPaymentResponse")
    @Action(input = "http://st.apus.com/STWS/confirmPaymentRequest", output = "http://st.apus.com/STWS/confirmPaymentResponse")
    public uz.maroqand.ecology.core.integration.upay.ConfirmPaymentResponse.Return confirmPayment(
            @WebParam(name = "confirmPaymentRequest", targetNamespace = "")
                    uz.maroqand.ecology.core.integration.upay.ConfirmPayment.ConfirmPaymentRequest confirmPaymentRequest);



}
